### ISSUE TITLE
Taxonomy writeup checklist

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/reference-taxonomy#260]
- [ ] **Main work on article content:**
    - [x] review revised outline (see [outline.md](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/examples/doc/method/outline.md)) and bring text into line with it
    - [x] decide what can be cut
    - [x] fold in text from poster
    - [x] introduction: 
        - [x] explain open tree project as a whole, plainly and simply
        - [x] define 'homonym' as term of art with special meaning local to this
            article (encompassing both taxonomic homonyms and hemihomonyms),
            and replace 'polysemy' which doesn't work (or: think of a different
            word to use)
        - [x] track down reference for technical term 'name-string'
        - [x] move the current 'complications' material to methods section
            (per NF and KC suggestion.)
    - [x] materials & methods:
        - [x] split into basic overview (with examples) and elaboration, per NF
        - [x] clean up organization
        - [x] track down GBIF references (blog posts, github repos)
        - [x] change 'union' to 'workspace' and 'skeleton' to 'barrier' per poster
        - [x] fold in align/merge figures from poster
        - [x] prepare figures based on poster (EPS, PNG, etc.)
        - [x] write a script to obtain the numbers that are in the source
            table (for reproducibility)
        - [x] simplify merge section - only need to talk about graft and insertion,
            not the recursive descent
        - [x] make sure that heuristic names are used consistently between
            methods and results sections
        - [x] describe the more important flags / annotations
        - [x] **must do**: explain that tips are aligned first, so that they can be used in computing the overlap alignment heuristic
    - [x] results:
        - [x] review for meaningfulness, strength, and truth of conclusions
        - [x] put explanations for alignment result lines directly into the table(s)
        - [x] remove Ruggiero section - can't figure out how to make it
            informative of anything at all.
        - [x] see how many of the hemihomonyms we have from HHDB? (but what do we learn from this?)
    - [ ] discussion:
        - [ ] go through references list to see which should be discussed
        - [x] expand or cut each of the 18 or so suggested thing-to-discuss
    - [x] address all other KC and NF comments

- [x] **Finish up article content:**
    - [x] write conclusions section
    - [x] review abstract, rewrite if necessary

- [x] **Smasher / OTT work:**
    - [x] find the most recent working (tests pass) commit of ref-tax.
    - [x] bring code in experimental branch for counting ad hoc alignments
        and patches into trunk (code works, but is in a branch with code
        that doesn't work)
    - [x] merge in anything else that's important or helpful from experimental
        branch, leaving broken stuff behind.
    - [x] re-run all the metrics and add to tables/figures
    - [x] make sure scripts are available/documented for all numbers in
        results section
    - [x] ensure build from fresh reference-taxonomy repo clone
    - [x] commit changes, make tag, etc.

- [ ] **Submission mechanics:**
    - [x] choose journal
    - [x] choose article type (software description, or methods?)
    - [ ] convert text to publisher demanded form (e.g. Arpha Writing Tool AWT)
    - [ ] convert references, tables, and figures to journal-demanded format
    - [ ] upload references, tables, figures
    - [ ] upload supplementary material if any (OTT?)
    - [ ] submit

**Comment by jar398** [comment]
added to checklist: 'describe the more important flags / annotations'

**Comment by jar398** [comment]
added to checklist: '**must do**: explain that tips are aligned first, so that they can be used in computing the overlap alignment heuristic'
